export default {
  base: '/',
  lang: 'ja',
  title: 'LeadGrid Docs for developers',
  description: 'Just playing around.',
  publicURL: 'http://localhost:300',
  head: [
  ],
  sidebar: [
    {
      title: 'イントロダクション',
      links: [
        { title: 'LeadGridとは', href: '/getting-started' },
      ],
    },
    {
      title: 'チュートリアル',
      links: [
        { title: '必要なツールやアカウントを揃えよう', href: '/installation' },
        { title: 'ローカルでコーディングしてみよう', href: '/installation' },
        { title: 'ステージング環境へデプロイして、固定ページを表示してみよう', href: '/installation' },
        { title: '投稿種別を作成し、動的ページを表示してみよう', href: '/installation' },
        { title: 'フォームを作成し、サイトに表示してみよう', href: '/installation' },
        { title: '本番環境へデプロイしてみよう', href: '/installation' },
      ],
    },
    {
      title: 'ヘルパー関数',
      links: [
        { title: 'editable_each_v2', href: '/roadmap' },
        { title: 'editable_text_v2', href: '/roadma2p' },
        { title: 'editable_link_v2', href: '/roadma2p' },
        { title: 'editable_image_v2', href: '/roadma2p' },
        { title: 'editable_background_v2', href: '/roadma2p' },
        { title: 'editable_form_v2', href: '/roadma2p' },
        { title: 'editable_date', href: '/roadma2p' },
        { title: 'editable_wysiwyg', href: '/roadma2p' },
        { title: 'editable_each', href: '/roadma2p' },
        { title: 'editable_start', href: '/roadma2p' },
        { title: 'editable_end', href: '/roadma2p' },
        { title: 'editable_link', href: '/roadma2p' },
        { title: 'editable_text', href: '/roadma2p' },
        { title: 'editable_background', href: '/roadma2p' },
        { title: 'editable_image', href: '/roadma2p' },
        { title: 'editable_display', href: '/roadma2p' },
        { title: 'debug', href: '/roadma2p' },
        { title: 'concat', href: '/roadma2p' },
        { title: 'day_of_week', href: '/roadma2p' },
        { title: 'leadgrid_form', href: '/roadma2p' },
        { title: 'make_color_thin', href: '/roadma2p' },
        { title: 'url_encode', href: '/roadma2p' },
        { title: 'amp', href: '/roadma2p' },
        { title: 'form_field_error', href: '/roadma2p' },
        { title: 'form_options', href: '/roadma2p' },
        { title: 'first', href: '/roadma2p' },
        { title: 'leadgrid_form_param', href: '/roadma2p' },
        { title: 'switch', href: '/roadma2p' },
        { title: 'and', href: '/roadma2p' },
        { title: 'trim_string', href: '/roadma2p' },
        { title: 'or', href: '/roadma2p' },
        { title: 'ifvalue', href: '/roadma2p' },
        { title: 'search_string', href: '/roadma2p' },
        { title: '@site', href: '/roadma2p' },
        { title: 'pagination', href: '/roadma2p' },
        { title: 'get_recaptcha_secret', href: '/roadma2p' },
        { title: 'footer', href: '/roadma2p' },
        { title: 'header', href: '/roadma2p' },
        { title: 'seo_tag', href: '/roadma2p' },
        { title: 'build_in_tag_v2', href: '/roadma2p' },
        { title: 'embed_script_tag', href: '/roadma2p' },
        { title: 'favicon_tag', href: '/roadma2p' },
        { title: 'seo_tag_v2', href: '/roadma2p' },
        { title: 'csrf', href: '/roadma2p' },
        { title: 'form_field', href: '/roadma2p' },
        { title: 'editable_form', href: '/roadma2p' },
        { title: 'link_class', href: '/roadma2p' },
        { title: 'img_url', href: '/roadma2p' },
        { title: 'date', href: '/roadma2p' },
        { title: 'terms', href: '/roadma2p' },
        { title: 'post', href: '/roadma2p' },
        { title: 'get', href: '/roadma2p' },
      ],
    },
    {
      title: 'その他',
      links: [
        { title: 'テクニカルSEO機能', href: '/roadma2p' },
      ]
    }
  ],
  search: {
    enabled: true,
  },
  editLink: {
    enabled: false,
  },
};
